-- MedChain: users table schema for Supabase
-- Safe to re-run: uses IF NOT EXISTS and drops policies before recreating.
-- Paste this into Supabase SQL Editor and click RUN.

-- 1. Create table (safe if already exists)
CREATE TABLE IF NOT EXISTS users (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           TEXT NOT NULL,
  email          TEXT UNIQUE NOT NULL,
  password       TEXT NOT NULL DEFAULT '',
  wallet_address TEXT UNIQUE NOT NULL,
  role           TEXT NOT NULL CHECK (role IN ('manufacturer','distributor','wholesaler','pharmacist','customer','admin')),
  facility_name  TEXT,
  license_number TEXT,
  contact_phone  TEXT,
  reason_for_access TEXT,
  status         TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  admin_note     TEXT,
  approved_at    TIMESTAMPTZ,
  created_at     TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Add columns if they were missing from an earlier run
ALTER TABLE users ADD COLUMN IF NOT EXISTS password       TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS facility_name  TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS license_number TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS contact_phone  TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS reason_for_access TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS admin_note     TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS approved_at    TIMESTAMPTZ;

-- 3. Enable Row Level Security
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- 4. Drop old policies first so re-runs never fail
DROP POLICY IF EXISTS "Allow public insert users" ON users;
DROP POLICY IF EXISTS "Allow public read users"   ON users;
DROP POLICY IF EXISTS "Allow public update users" ON users;
DROP POLICY IF EXISTS "Allow public delete users" ON users;

-- 5. Recreate policies
CREATE POLICY "Allow public insert users" ON users FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read users"   ON users FOR SELECT USING (true);
CREATE POLICY "Allow public update users" ON users FOR UPDATE USING (true);
CREATE POLICY "Allow public delete users" ON users FOR DELETE USING (true);
